NODENV_INSTALLED_VERSIONS=$(nodenv-versions --bare --skip-aliases)
LTS_INSTALL_ROOT=$(plugin_root)
LTS_INSTALL_BUILD_DEFINITIONS="$LTS_INSTALL_ROOT/share/versions"
NODE_BUILD_DEFINITIONS=$NODE_BUILD_DEFINITIONS:$LTS_INSTALL_BUILD_DEFINITIONS
FINAL_VERSION=""

if [ -n "$NODENV_INSTALLED_VERSIONS" ]; then
  FINAL_VERSION=$(nodenv-lts-install "$LTS_INSTALL_BUILD_DEFINITIONS" "$1")

  if [ -n "$FINAL_VERSION" ]; then
    echo "lts-install: $1 => $FINAL_VERSION"
    DEFINITION=$FINAL_VERSION
  fi
fi

unset FINAL_VERSION
unset LTS_INSTALL_BUILD_DEFINITIONS
unset LTS_INSTALL_ROOT
unset NODENV_INSTALLED_VERSIONS
